name: 'Auth0 Remove Origin'
description: 'Remove an origin URL from an Auth0 client'
inputs:
  domain:
    description: "Auth0 domain (tenant)"
    required: true
  clientId:
    description: "Auth0 Client ID"
    required: true
  clientSecret:
    description: "Auth0 Client Secret"
    required: true
  origin:
    description: "The allowed web origin to remove"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'