name: Twistlock
description: Run Twistlock

inputs:
  username:
    description: User for authenticating with Prisma Cloud Console.
    required: true
  password:
    description: Password for authenticating with Prisma Cloud Console.
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
