name: Twistlock
description: Run Twistlock

inputs:
  project:
    description: Specifies a target project
    required: true
  consuleURL:
    description: Prisma Cloud Console's URL
    required: true
  username:
    description: User for authenticating with Prisma Cloud Console.
    required: true
  password:
    description: Password for authenticating with Prisma Cloud Console.
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
