name: Twistlock
description: Run Twistlock

inputs:
  tl-project:
    description: Specifies a target project
    required: true
    default: Titan-QA
  tl-username:
    description: User for authenticating with Prisma Cloud Console.
    required: true
    default: jenkins
  tl-password:
    description: Password for authenticating with Prisma Cloud Console.
    required: true
    default: jenkins
  tl-console-url:
    description: Prisma Cloud Console's URL
    required: true
    default: https://twistlock.cloud.resideo.com
  tl-cli-version:
    description: The version of the twistlock cli
    required: true
    default: v1
  tl-path:
    description: Path to scan
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Download CLI from Twistlock console
      shell: bash
      run: |
        curl \
          --insecure \
          --user "${{ inputs.tl-username }}:${{ inputs.tl-password }}" \
          --output ./twistcli \
          "${{ inputs.tl-console-url }}/api/${{ inputs.tl-cli-version }}/util/twistcli"
        chmod a+x ./twistcli
    - name: Scan the image using the Twistlock CLI
      shell: bash
      run: |
        ./twistcli coderepo scan \
          --ci \
          --details \
          --project "${{ inputs.tl-}}" \
          --address "${{ inputs.tl-console-url }}" \
          --user "${{ inputs.tl-username }}" \
          --password "${{ inputs.tl-password }}" \
          --output-file ".twistlock-result.json" \
          ${{ inputs.tl-path }}
    - name: Post a comment result
      uses: actions/github-script@v4
      with:
        script: |
          const results = require("./.twistlock-result.json");
          const script = require('./dist/index.js')
          await script.writeSummary({ github, context, core, results })