name: 'Auth0 Add Origin'
description: 'Add an allowed origin URL to an Auth0 client'
inputs:
  domain:
    description: "Auth0 domain (tenant)"
    required: true
  apiClientId:
    description: "Auth0 Client ID for the M2M API application"
    required: true
  apiClientSecret:
    description: "Auth0 Client Secret for the M2M API application"
    required: true
  clientId:
    description: "Auth0 Client ID of the application to be updated"
    required: true
  origin:
    description: "The allowed web origin to add"
    required: true
  callbackUrl:
    description: "The allowed callback URL to add. Will fallback to origin if not provided"
    required: false
  logoutUrl:
    description: "The allowed logout URL to add. Will fallback to origin if not provided"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'